// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs0hOwhXhb3rz2NOlsboSFORZOWZ0BQ44',
    appId: '1:332602737030:web:3182f3d95182cdf752ec07',
    messagingSenderId: '332602737030',
    projectId: 'xlr8-6b14e',
    authDomain: 'xlr8-6b14e.firebaseapp.com',
    storageBucket: 'xlr8-6b14e.appspot.com',
    measurementId: 'G-X2J9K67MK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TbFogXZSKVkdHBriE7cHGW9B2hXM44k',
    appId: '1:332602737030:android:4250c24654a4c4b852ec07',
    messagingSenderId: '332602737030',
    projectId: 'xlr8-6b14e',
    storageBucket: 'xlr8-6b14e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrc35C5iCrMqNXiwXk8a8b1DKBL6C_jRg',
    appId: '1:332602737030:ios:687e2c732fc19f3452ec07',
    messagingSenderId: '332602737030',
    projectId: 'xlr8-6b14e',
    storageBucket: 'xlr8-6b14e.appspot.com',
    iosClientId: '332602737030-j5pcelp2974enpffrfs43kftqqbjimuk.apps.googleusercontent.com',
    iosBundleId: 'com.xm.grex.arms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrc35C5iCrMqNXiwXk8a8b1DKBL6C_jRg',
    appId: '1:332602737030:ios:ab9faa0746c5076a52ec07',
    messagingSenderId: '332602737030',
    projectId: 'xlr8-6b14e',
    storageBucket: 'xlr8-6b14e.appspot.com',
    iosClientId: '332602737030-uardam2s87ikvk36r49d2rvk7e5aj4ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.arms',
  );
}
